# Generated by Django 5.0.6 on 2024-07-08 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gptapp', '0002_remove_novelproject_updated_at_novelproject_outline'),
    ]

    operations = [
        migrations.AddField(
            model_name='novelproject',
            name='chapter',
            field=models.IntegerField(default=0),
        ),
    ]
